from biology.curriculum._factory import _r

RECORDS = (
    _r(
        "unit_VII_bacteria_archaea_viruses",
        "Microbial diversity reflects different cell architectures, genomes, metabolisms, and evolutionary histories.",
        ("prokaryotic structure", "archaea", "viruses", "horizontal gene transfer"),
        "Growth-rate, genome-size, and dilution calculations.",
        "Interpret microbial observations from growth, sequence, or structural evidence.",
        "Measure growth and compare microbial life strategies.",
        "Viruses are not simply tiny bacteria; they use fundamentally different replication logic.",
        "Classify a microbe or virus from evidence and predict a likely vulnerability.",
        "Apply microbial diversity reasoning to antibiotics, biotechnology, ecology, and outbreaks.",
        "biology.microbiology.microbiology.bacterial_growth_curve",
    ),
    _r(
        "unit_VII_microbial_ecology",
        "Microbes organize communities, cycles, and host physiology through interactions and metabolism.",
        ("microbiomes", "symbiosis", "diversity", "biogeochemical cycling"),
        "Diversity indices, richness estimates, and interaction-network reasoning.",
        "Compute or interpret community metrics from abundance data.",
        "Compare microbial communities and infer interaction hypotheses.",
        "A microbiome is not automatically beneficial; context determines the effect.",
        "Use community data to infer diversity, dominance, and a plausible ecological mechanism.",
        "Transfer microbial ecology to soils, oceans, digestion, disease, and climate feedbacks.",
        "biology.ecology.ecology.biodiversity_indices",
    ),
    _r(
        "unit_VII_host_immunity_and_vaccines",
        "Host immunity and vaccination reshape pathogen transmission by changing susceptible fractions.",
        ("innate immunity", "adaptive immunity", "vaccination", "herd immunity"),
        "Herd-immunity threshold and basic immunological reasoning.",
        "Interpret antibody, cellular, and vaccine-response evidence.",
        "Compare immune mechanisms and vaccination scenarios.",
        "Immunity is not binary; timing, dose, and variant matter.",
        "Predict how immunity or vaccination changes individual and population risk.",
        "Transfer immunity reasoning to outbreak response and clinical decision-making.",
        "biology.microbiology.microbiology.sir_model",
    ),
    _r(
        "unit_VII_antimicrobial_resistance_and_epidemiology",
        "Antimicrobial resistance and epidemic dynamics emerge from pathogen evolution and transmission networks.",
        ("antibiotic resistance", "R0", "transmission", "surveillance"),
        "R0, resistance-mechanism, and outbreak-trajectory calculations.",
        "Interpret resistance assays and outbreak curves.",
        "Model transmission and compare resistance-control strategies.",
        "R0 is not a fixed property of a pathogen alone; it depends on host behavior and environment.",
        "Calculate a threshold or outbreak trajectory and identify the intervention lever.",
        "Transfer resistance and epidemiology reasoning to stewardship and public-health policy.",
        "biology.microbiology.microbiology.sir_model",
    ),
)
