from biology.curriculum._factory import _r

RECORDS = (
    _r(
        "unit_IV_dna_replication_and_cell_cycle",
        "Genome copying is accurate because chemistry, enzyme proofreading, and checkpoints cooperate.",
        ("semiconservative replication", "polymerase", "proofreading", "checkpoints"),
        "Replication-fork speed, error-rate, and cell-cycle timing calculations.",
        "Interpret replication or cell-cycle data from timing, labeling, or checkpoint perturbations.",
        "Model replication dynamics and checkpoint outcomes.",
        "High fidelity is not automatic; it is built from multiple partially redundant safeguards.",
        "Calculate replication timing or error burden and infer checkpoint consequences.",
        "Transfer replication logic to cancer, aging, viral replication, or antibiotic targets.",
        "biology.genetics.genetics.dna_complement",
    ),
    _r(
        "unit_IV_gene_expression",
        "Gene expression translates sequence information into regulated RNA and protein products.",
        ("transcription", "translation", "codons", "RNA processing"),
        "Reading-frame, codon, and expression-output calculations.",
        "Convert DNA/RNA sequence data into predicted molecular products.",
        "Trace expression from DNA template to protein or regulatory RNA.",
        "A gene is not simply a protein recipe; context controls when, where, and how much product appears.",
        "Translate or annotate a sequence and explain how a regulatory change alters output.",
        "Apply expression logic to mutations, biotechnology, development, and disease diagnostics.",
        "biology.genetics.genetics.translate_mrna",
    ),
    _r(
        "unit_IV_mutations_and_genomics",
        "Genomic variation becomes biological consequence through sequence context, repair, and selection.",
        ("mutation classes", "DNA repair", "CRISPR", "genome analysis"),
        "Mutation-rate, edit-efficiency, and sequence-comparison calculations.",
        "Classify variants and predict likely molecular effect from sequence evidence.",
        "Evaluate genome-editing or variant-calling scenarios.",
        "Not every mutation is harmful, and not every harmful mutation changes a protein sequence.",
        "Predict the impact of a variant and justify the evidence needed to validate it.",
        "Transfer variant reasoning to cancer genomics, ancestry, gene therapy, or microbial evolution.",
        "biology.genetics.genetics.hamming_distance",
    ),
    _r(
        "unit_IV_chromatin_and_epigenetic_mechanisms",
        "Cells create stable yet reversible expression states through chromatin, DNA marks, and regulatory circuits.",
        ("chromatin", "methylation", "histone modification", "enhancers"),
        "Regulatory-state and expression-ratio reasoning.",
        "Interpret chromatin or expression evidence from simple regulatory datasets.",
        "Compare regulatory perturbations and predicted expression outputs.",
        "Epigenetic does not mean independent of DNA sequence or permanently inherited.",
        "Explain how a regulatory mark changes accessibility and predict downstream expression.",
        "Apply regulation logic to differentiation, imprinting, cancer, or environmental responses.",
        "biology.genetics.genetics.cpg_methylation_remaining",
    ),
    _r(
        "unit_IV_epigenetic_inheritance_and_disease",
        "Three-dimensional genome organization and epigenetic inheritance link regulatory architecture to disease phenotypes.",
        ("3D genome", "phase separation", "imprinting", "epigenetic inheritance"),
        "Chromatin-loop, inheritance, and disease-risk reasoning.",
        "Interpret Hi-C, imprinting, or transgenerational datasets with causal caution.",
        "Compare inheritance models and predict disease consequences of regulatory disruption.",
        "A chromatin contact map is not proof of function without perturbation.",
        "Explain how 3D organization or inherited marks alter expression and disease risk.",
        "Apply inheritance logic to cancer, developmental disorders, and environmental exposure.",
        "biology.genetics.genetics.histone_modification_state",
    ),
)
