from biology.curriculum._factory import _r

RECORDS = (
    _r(
        "unit_V_mendelian_principles",
        "Mendelian segregation and probability explain inheritance when alleles assort independently.",
        ("segregation", "independent assortment", "Punnett squares", "probability"),
        "Punnett, binomial, and chi-square calculations.",
        "Use cross data to infer genotype probabilities.",
        "Solve monohybrid and dihybrid crosses and test expected ratios.",
        "Dominant does not mean common, stronger, or better.",
        "Compute a genetic probability or chi-square result and explain the biological assumption.",
        "Transfer Mendelian probability to model organisms and introductory human genetics.",
        "biology.genetics.genetics.chi_squared_test",
    ),
    _r(
        "unit_V_mendelian_extensions_and_human_genetics",
        "Extensions to Mendelian ratios and human pedigree analysis reveal when simple dominance fails.",
        ("incomplete dominance", "epistasis", "pedigrees", "penetrance"),
        "Pedigree, epistasis, and multi-locus probability calculations.",
        "Infer inheritance mode and extension mechanism from family or cross data.",
        "Solve pedigree and extension problems with explicit assumptions.",
        "A single-gene model is a starting hypothesis, not the default for every trait.",
        "Use pedigree or extension evidence to justify an inheritance diagnosis.",
        "Transfer extension reasoning to counseling, GWAS interpretation, and breeding.",
        "biology.genetics.genetics.punnett_square",
    ),
    _r(
        "unit_V_chromosomal_inheritance",
        "Genes travel on chromosomes, so linkage, recombination, and chromosome structure shape inheritance.",
        ("linkage", "recombination", "sex linkage", "chromosomal rearrangements"),
        "Recombination frequency and three-point mapping.",
        "Infer gene order or chromosomal mechanism from offspring counts.",
        "Map linked genes and reason from chromosomal anomalies.",
        "Independent assortment applies to unlinked loci, not to every pair of genes.",
        "Use progeny classes to calculate map distances and infer the most likely gene order.",
        "Transfer linkage reasoning to disease mapping, breeding, and genome assemblies.",
        "biology.genetics.genetics.infer_three_point_order",
    ),
    _r(
        "unit_V_population_genetics",
        "Allele frequencies change when assumptions about random mating, population size, and fitness are violated.",
        ("Hardy-Weinberg", "selection", "mutation", "genetic drift"),
        "Hardy-Weinberg and allele-frequency recurrence calculations.",
        "Estimate genotype or allele frequencies from population data.",
        "Test equilibrium and model allele-frequency change.",
        "Hardy-Weinberg is a null model, not a claim that populations do not evolve.",
        "Calculate expected frequencies and identify which evolutionary force could explain deviations.",
        "Apply population-genetic reasoning to screening, conservation, and pathogen evolution.",
        "biology.genetics.genetics.hardy_weinberg",
    ),
)
