from biology.curriculum._factory import _r

RECORDS = (
    _r(
        "unit_X_population_ecology",
        "Population change reflects births, deaths, movement, age structure, and density dependence.",
        ("exponential growth", "logistic growth", "life tables", "population viability"),
        "Exponential/logistic growth, mark-recapture, and matrix projection.",
        "Use abundance or age-structure data to estimate growth and risk.",
        "Model population trajectories and compare sampling methods.",
        "Carrying capacity is not a fixed magic number; it changes with resources, interactions, and disturbance.",
        "Calculate a growth or sampling parameter and interpret its conservation meaning.",
        "Transfer population models to fisheries, invasive species, epidemiology, and endangered species.",
        "biology.ecology.ecology.logistic_growth",
    ),
    _r(
        "unit_X_community_interactions",
        "Communities are structured by pairwise species interactions and successional change.",
        ("competition", "predation", "mutualism", "succession"),
        "Lotka-Volterra-style interaction reasoning.",
        "Interpret abundance, interaction, or disturbance data from communities.",
        "Compare species-interaction outcomes under changing conditions.",
        "A species interaction is not permanently good or bad; the sign can change with context.",
        "Predict how changing one species or resource alters community structure.",
        "Transfer interaction reasoning to restoration, agriculture, and invasion biology.",
        "biology.ecology.ecology.biodiversity_indices",
    ),
    _r(
        "unit_X_biodiversity_and_food_webs",
        "Biodiversity patterns, food webs, and island biogeography scale from local interactions to landscape structure.",
        ("food webs", "keystone species", "species-area", "diversity indices"),
        "Shannon, species-area, and network connectance reasoning.",
        "Interpret food-web, richness, or biogeography datasets.",
        "Compare diversity and network scenarios under area or disturbance change.",
        "Richness alone does not equal functional stability.",
        "Calculate a diversity or species-area metric and interpret its ecological meaning.",
        "Transfer biodiversity reasoning to conservation planning and habitat fragmentation.",
        "biology.ecology.ecology.species_area_relationship",
    ),
    _r(
        "unit_X_ecosystem_ecology",
        "Ecosystems couple energy flow and matter cycling across organisms, environments, and time.",
        ("primary productivity", "trophic efficiency", "nutrient cycles", "decomposition"),
        "Energy-flow, productivity, and nutrient-budget calculations.",
        "Trace matter and energy through food webs and biogeochemical cycles.",
        "Quantify ecosystem fluxes and identify limiting pools.",
        "Energy flows through ecosystems, but matter cycles; confusing the two breaks many explanations.",
        "Calculate a flux or efficiency and explain which pool or process limits the system.",
        "Transfer ecosystem reasoning to eutrophication, carbon budgets, agriculture, and climate feedback.",
        "biology.ecology.ecology.food_web_trophic_levels",
    ),
    _r(
        "unit_X_biomes_and_conservation",
        "Biodiversity patterns and conservation decisions emerge from climate, history, disturbance, and human choice.",
        ("biomes", "biodiversity", "extinction risk", "conservation planning"),
        "Species-area, risk, and prioritization calculations.",
        "Use maps, trend data, and threat categories to justify conservation priorities.",
        "Compare biome patterns and conservation tradeoffs.",
        "Conservation is decision-making under constraints and uncertainty, not only preserving untouched nature.",
        "Evaluate a conservation scenario using evidence, tradeoffs, and uncertainty.",
        "Transfer conservation reasoning to land use, climate corridors, restoration, and environmental justice.",
        "biology.ecology.ecology.species_area_relationship",
    ),
)
