from biology.curriculum._factory import _r

RECORDS = (
    _r(
        "unit_IX_circulation_respiration_homeostasis",
        "Animal transport systems maintain gradients that let cells exchange gases, nutrients, heat, and wastes.",
        ("cardiac output", "gas exchange", "homeostasis", "feedback"),
        "Cardiac-output, diffusion, oxygen-saturation, and feedback calculations.",
        "Interpret physiological data from pressure, flow, saturation, or set-point changes.",
        "Model circulation, respiration, and feedback compensation.",
        "Homeostasis is dynamic regulation, not an unchanging internal state.",
        "Calculate a transport or feedback variable and explain the compensatory response.",
        "Transfer homeostatic reasoning to exercise, altitude, hemorrhage, fever, and shock.",
        "biology.physiology.physiology.oxygen_saturation",
    ),
    _r(
        "unit_IX_nervous_system",
        "Nervous systems compute with cells whose structure shapes information flow and behavior.",
        ("neurons", "glia", "circuits", "sensory processing"),
        "Cable-length, conduction, and simple circuit calculations.",
        "Interpret neural data from anatomy, timing, or lesion evidence.",
        "Map circuit structure onto predicted information flow.",
        "The brain is not only neurons; glia and circuit context are essential to function.",
        "Predict behavioral or signal consequences from a circuit or structural perturbation.",
        "Transfer circuit reasoning to reflexes, sensory systems, learning, and disease.",
        "biology.neuroscience.neuroscience.cable_voltage_attenuation",
    ),
    _r(
        "unit_IX_action_potential_synapses",
        "Electrical excitability and synaptic transmission convert ion gradients into rapid communication.",
        ("action potentials", "ion channels", "synapses", "plasticity"),
        "Nernst/Goldman, Hodgkin-Huxley, and synaptic-current reasoning.",
        "Interpret voltage traces, conductance changes, and synaptic perturbations.",
        "Model excitability and synaptic response under changed ion or channel conditions.",
        "An action potential is not electricity flowing like a wire; it is regenerated ion-channel dynamics.",
        "Predict how changing an ion gradient or channel conductance alters excitability.",
        "Transfer excitability reasoning to anesthesia, toxins, epilepsy, and neuromuscular disease.",
        "biology.neuroscience.neuroscience.action_potential_hh",
    ),
    _r(
        "unit_IX_endocrine_signaling",
        "Hormone feedback loops coordinate long-range physiological homeostasis.",
        ("hormones", "feedback", "receptors", "homeostasis"),
        "Hormone feedback and dose-response reasoning.",
        "Interpret endocrine time courses, panels, and perturbations.",
        "Compare endocrine axes and feedback scenarios.",
        "A hormone surge is not always pathological; context and set-point matter.",
        "Predict the consequence of changing a hormone, receptor, or axis set-point.",
        "Transfer endocrine reasoning to metabolism, stress, and development.",
        "biology.physiology.physiology.homeostasis_response",
    ),
    _r(
        "unit_IX_immune_system_defense",
        "Innate and adaptive immunity integrate recognition, effector function, tolerance, and memory.",
        ("innate immunity", "adaptive immunity", "tolerance", "immunotherapy"),
        "Immune-memory, cytokine, and recognition reasoning.",
        "Interpret immune titers, cytokine profiles, or perturbation data.",
        "Compare innate and adaptive activation scenarios.",
        "Immunity is not just attack; recognition, tolerance, memory, and regulation are equally central.",
        "Predict the consequence of changing an antigen, cell population, or checkpoint.",
        "Transfer immunity reasoning to vaccination, autoimmunity, infection, and cancer therapy.",
        "biology.physiology.physiology.homeostasis_response",
    ),
)
