from biology.curriculum._factory import _r

RECORDS = (
    _r(
        "unit_II_cell_theory",
        "Cells are bounded, evolving systems whose size and organization reflect physical constraints.",
        ("cell theory", "surface area", "microscopy", "prokaryote/eukaryote comparison"),
        "Surface-area-to-volume scaling.",
        "Infer cellular constraints from measurements, micrographs, and scale bars.",
        "Compare cell types and quantify surface-area limits.",
        "Cells are not just small bags of fluid; boundaries and internal organization create function.",
        "Use size or microscopy evidence to classify a cell and predict a constraint on exchange.",
        "Transfer scale reasoning to eggs, neurons, root hairs, and microbial colonies.",
        "biology.cell.cell_biology.diffusion_flux",
    ),
    _r(
        "unit_II_cell_structure",
        "Organelle structure partitions work, traffic, information, and energy inside eukaryotic cells.",
        ("organelles", "endomembrane system", "cytoskeleton", "motor proteins"),
        "Compartment-flow and motor-transport calculations.",
        "Trace a molecule through compartments using evidence from labels or perturbations.",
        "Map organelle function with microscopy-style observations.",
        "Organelles are dynamic process hubs, not static textbook icons.",
        "Predict which organelle or cytoskeletal process is disrupted from a phenotype.",
        "Apply compartment logic to secretion, apoptosis, infection, or cell division.",
        "biology.cell.cell_biology.ORGANELLES",
    ),
    _r(
        "unit_II_membrane_transport",
        "Membranes convert gradients, permeability, and selective transport into cellular physiology.",
        ("bilayers", "diffusion", "osmosis", "electrochemical gradients"),
        "Nernst, Goldman, osmotic, and facilitated-transport calculations.",
        "Interpret transport data from gradients, rates, and membrane potentials.",
        "Test osmosis and transport mechanisms with simple cell or model-membrane observations.",
        "Equilibrium does not mean equal concentration; charge and permeability matter.",
        "Calculate or predict ion movement and explain which force dominates.",
        "Transfer gradient logic to neurons, kidneys, roots, and mitochondrial membranes.",
        "biology.cell.cell_biology.nernst_potential",
    ),
    _r(
        "unit_II_cell_signaling",
        "Cells communicate by converting external signals into regulated intracellular decisions.",
        ("receptors", "second messengers", "signal amplification", "feedback"),
        "Ligand-receptor occupancy and dose-response reasoning.",
        "Read pathway diagrams and infer the effect of agonists, antagonists, or mutations.",
        "Model signaling response from receptor activation to cellular output.",
        "A pathway diagram is a causal model, not a memorization chart.",
        "Predict the outcome of perturbing one pathway component and justify the causal chain.",
        "Apply signaling logic to hormones, neurotransmitters, immune receptors, or cancer mutations.",
        "biology.physiology.physiology.homeostasis_response",
    ),
)
