from biology.curriculum._factory import _r

RECORDS = (
    _r(
        "unit_0_systems_science",
        "Biological explanation improves when parts, interactions, feedback, and scale are kept in view together.",
        ("systems boundaries", "feedback", "emergence", "state variables"),
        "Box-and-arrow causal models with explicit inputs, outputs, and feedback signs.",
        "Translate a verbal biological system into variables, links, and testable predictions.",
        "Build and critique a feedback model for a familiar living system.",
        "A system is not just a list of parts; the interactions are part of the explanation.",
        "Given a biological scenario, identify the system boundary, feedback loop, and missing measurement.",
        "Apply the same feedback map to a cell, organism, and ecosystem, then name what changes at each scale.",
        "biology.crossref_validator.validate",
    ),
    _r(
        "unit_0_complex_adaptive_systems",
        "Local rules can generate population-level patterns without a central controller.",
        ("nonlinearity", "self-organization", "attractors", "power laws"),
        "Agent-rule and scaling arguments for emergent biological patterns.",
        "Distinguish deterministic trends from stochastic variation in repeated simulations.",
        "Explore how small rule changes alter collective behavior.",
        "Emergence is not mysterious; it is a reproducible consequence of interactions plus constraints.",
        "Explain an observed population pattern from individual-level rules and identify one falsifiable prediction.",
        "Compare flocking, immune activation, and microbial biofilms as adaptive systems.",
        "biology.ecology.ecology.logistic_growth",
    ),
    _r(
        "unit_0_active_inference",
        "Living systems reduce uncertainty by acting on the world as well as by updating internal models.",
        ("prediction error", "Bayesian updating", "policy selection", "homeostasis"),
        "Bayesian belief updating and expected-free-energy-style policy comparison.",
        "Read a small probability table and update a prediction after new evidence.",
        "Model sensing and action as coupled inference in a simple organism.",
        "Active inference is not passive prediction; action changes the sensory data that arrive next.",
        "Calculate a posterior belief and explain what action would reduce uncertainty or restore a set point.",
        "Map prediction-error reasoning onto chemotaxis, thermoregulation, and attention.",
        "biology.physiology.physiology.homeostasis_response",
    ),
    _r(
        "unit_0_history_philosophy_biology",
        "Biology is a changing evidence practice: its concepts of life, function, species, inheritance, and self are revised by new observations, instruments, models, and social values.",
        ("biological explanation", "historical evidence", "function", "species concepts", "values in science"),
        "Concept-map and evidence-matrix comparisons among historical claims, mechanisms, and model assumptions.",
        "Classify source excerpts as observation, experiment, model, mechanism, or value-laden inference.",
        "Analyze historical source cards and build an evidence map for a disputed biological claim.",
        "History is not a list of dates; it explains why current biological concepts are powerful, limited, and revisable.",
        "Given a biological claim, identify the practice that produced it, the evidence standard it used, and one philosophical assumption it carries.",
        "Transfer source-analysis reasoning to modern debates about species, genetics, microbiomes, and biomedical ethics.",
        "biology.toc.load_toc",
    ),
)
