from biology.curriculum._factory import _r

RECORDS = (
    _r(
        "unit_I_atoms_molecules",
        "Atomic structure constrains the bonds, charges, and geometries that make biological molecules possible.",
        ("valence", "electronegativity", "formal charge", "isotopes"),
        "Formal charge and electronegativity-difference reasoning.",
        "Use tabular atomic data to predict polarity, solubility, and biological reactivity.",
        "Classify bonds and solvent behavior using simple observations.",
        "Weak interactions are not unimportant; many weak interactions together dominate structure and specificity.",
        "Predict bond polarity, formal charge, or isotope behavior and connect it to a biological consequence.",
        "Use atomic reasoning to explain a medical tracer, enzyme cofactor, or membrane-solubility problem.",
        "biology.biochemistry.biochemistry.atp_free_energy",
    ),
    _r(
        "unit_I_water_and_life",
        "Water's polarity, hydrogen bonding, and ionization make cells physically possible.",
        ("hydrogen bonding", "cohesion", "pH", "buffers"),
        "Henderson-Hasselbalch and pH-scale calculations.",
        "Convert between pH, hydrogen ion concentration, and buffer ratios.",
        "Measure surface tension, polarity, and buffering behavior.",
        "Water is not an inert background; it is an active participant in structure and reaction chemistry.",
        "Calculate a pH or buffer ratio and interpret what it means for a biological system.",
        "Transfer water-property reasoning to blood buffering, plant transport, or protein folding.",
        "biology.biochemistry.biochemistry.atp_free_energy",
    ),
    _r(
        "unit_I_macromolecules",
        "Macromolecule structure links monomer chemistry to biological function and information storage.",
        ("polymers", "dehydration synthesis", "protein structure", "nucleic acids"),
        "Polymerization energetics and sequence-to-structure reasoning.",
        "Classify molecules from structural evidence rather than names alone.",
        "Use chemical tests and structural clues to identify biological macromolecules.",
        "Structure is not decoration; small chemical changes can redirect function and recognition.",
        "Given a molecular feature, infer likely solubility, interaction partners, or cellular role.",
        "Explain how a mutation, lipid substitution, or glycosylation change propagates to phenotype.",
        "biology.genetics.genetics.translate_mrna",
    ),
    _r(
        "unit_I_enzymes_and_kinetics",
        "Enzymes accelerate reactions by stabilizing transition states without changing thermodynamic endpoints.",
        ("activation energy", "Michaelis-Menten kinetics", "inhibition", "allostery"),
        "Michaelis-Menten, Lineweaver-Burk, and inhibition-pattern calculations.",
        "Fit or interpret enzyme-rate data and identify which parameter changed.",
        "Measure reaction-rate proxies and compare inhibition scenarios.",
        "A catalyst changes rate, not the equilibrium constant or the sign of delta G.",
        "Infer Vmax, Km, or inhibition type from data and justify the mechanistic interpretation.",
        "Apply enzyme-kinetic reasoning to drug dosing, metabolic control, or diagnostic assays.",
        "biology.biochemistry.biochemistry.michaelis_menten",
    ),
)
