"""Curriculum metadata for the biology textbook.

The records in this module are the pedagogical spine of the project. They
connect each chapter to a concise big idea, the model or data skill students
should practice, the matching lab/question-bank surfaces, and a misconception
that should be repaired explicitly.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CurriculumRecord:
    """Instructional metadata for one chapter and its companion materials."""

    chapter_id: str
    big_idea: str
    core_concepts: tuple[str, ...]
    quantitative_model: str
    data_skill: str
    lab_focus: str
    common_misconception: str
    assessment_focus: str
    transfer_task: str
    bridge_api: str

    @property
    def lab_label(self) -> str:
        return f"sec:lab_{self.chapter_id}"

    @property
    def question_label(self) -> str:
        return f"sec:q_{self.chapter_id}"


def _r(
    chapter_id: str,
    big_idea: str,
    core_concepts: tuple[str, ...],
    quantitative_model: str,
    data_skill: str,
    lab_focus: str,
    common_misconception: str,
    assessment_focus: str,
    transfer_task: str,
    bridge_api: str,
) -> CurriculumRecord:
    return CurriculumRecord(
        chapter_id=chapter_id,
        big_idea=big_idea,
        core_concepts=core_concepts,
        quantitative_model=quantitative_model,
        data_skill=data_skill,
        lab_focus=lab_focus,
        common_misconception=common_misconception,
        assessment_focus=assessment_focus,
        transfer_task=transfer_task,
        bridge_api=bridge_api,
    )


CURRICULUM: tuple[CurriculumRecord, ...] = (
    _r(
        "unit_0_systems_science",
        "Biological explanation improves when parts, interactions, feedback, and scale are kept in view together.",
        ("systems boundaries", "feedback", "emergence", "state variables"),
        "Box-and-arrow causal models with explicit inputs, outputs, and feedback signs.",
        "Translate a verbal biological system into variables, links, and testable predictions.",
        "Build and critique a feedback model for a familiar living system.",
        "A system is not just a list of parts; the interactions are part of the explanation.",
        "Given a biological scenario, identify the system boundary, feedback loop, and missing measurement.",
        "Apply the same feedback map to a cell, organism, and ecosystem, then name what changes at each scale.",
        "biology.crossref_validator.validate",
    ),
    _r(
        "unit_0_complex_adaptive_systems",
        "Local rules can generate population-level patterns without a central controller.",
        ("nonlinearity", "self-organization", "attractors", "power laws"),
        "Agent-rule and scaling arguments for emergent biological patterns.",
        "Distinguish deterministic trends from stochastic variation in repeated simulations.",
        "Explore how small rule changes alter collective behavior.",
        "Emergence is not mysterious; it is a reproducible consequence of interactions plus constraints.",
        "Explain an observed population pattern from individual-level rules and identify one falsifiable prediction.",
        "Compare flocking, immune activation, and microbial biofilms as adaptive systems.",
        "biology.ecology.ecology.logistic_growth",
    ),
    _r(
        "unit_0_active_inference",
        "Living systems reduce uncertainty by acting on the world as well as by updating internal models.",
        ("prediction error", "Bayesian updating", "policy selection", "homeostasis"),
        "Bayesian belief updating and expected-free-energy-style policy comparison.",
        "Read a small probability table and update a prediction after new evidence.",
        "Model sensing and action as coupled inference in a simple organism.",
        "Active inference is not passive prediction; action changes the sensory data that arrive next.",
        "Calculate a posterior belief and explain what action would reduce uncertainty or restore a set point.",
        "Map prediction-error reasoning onto chemotaxis, thermoregulation, and attention.",
        "biology.physiology.physiology.homeostasis_response",
    ),
    _r(
        "unit_0_history_philosophy_biology",
        "Biology is a changing evidence practice: its concepts of life, function, species, inheritance, and self are revised by new observations, instruments, models, and social values.",
        ("biological explanation", "historical evidence", "function", "species concepts", "values in science"),
        "Concept-map and evidence-matrix comparisons among historical claims, mechanisms, and model assumptions.",
        "Classify source excerpts as observation, experiment, model, mechanism, or value-laden inference.",
        "Analyze historical source cards and build an evidence map for a disputed biological claim.",
        "History is not a list of dates; it explains why current biological concepts are powerful, limited, and revisable.",
        "Given a biological claim, identify the practice that produced it, the evidence standard it used, and one philosophical assumption it carries.",
        "Transfer source-analysis reasoning to modern debates about species, genetics, microbiomes, and biomedical ethics.",
        "biology.toc.load_toc",
    ),
    _r(
        "unit_I_atoms_molecules",
        "Atomic structure constrains the bonds, charges, and geometries that make biological molecules possible.",
        ("valence", "electronegativity", "formal charge", "isotopes"),
        "Formal charge and electronegativity-difference reasoning.",
        "Use tabular atomic data to predict polarity, solubility, and biological reactivity.",
        "Classify bonds and solvent behavior using simple observations.",
        "Weak interactions are not unimportant; many weak interactions together dominate structure and specificity.",
        "Predict bond polarity, formal charge, or isotope behavior and connect it to a biological consequence.",
        "Use atomic reasoning to explain a medical tracer, enzyme cofactor, or membrane-solubility problem.",
        "biology.biochemistry.biochemistry.atp_free_energy",
    ),
    _r(
        "unit_I_water_and_life",
        "Water's polarity, hydrogen bonding, and ionization make cells physically possible.",
        ("hydrogen bonding", "cohesion", "pH", "buffers"),
        "Henderson-Hasselbalch and pH-scale calculations.",
        "Convert between pH, hydrogen ion concentration, and buffer ratios.",
        "Measure surface tension, polarity, and buffering behavior.",
        "Water is not an inert background; it is an active participant in structure and reaction chemistry.",
        "Calculate a pH or buffer ratio and interpret what it means for a biological system.",
        "Transfer water-property reasoning to blood buffering, plant transport, or protein folding.",
        "biology.biochemistry.biochemistry.atp_free_energy",
    ),
    _r(
        "unit_I_macromolecules",
        "Macromolecule structure links monomer chemistry to biological function and information storage.",
        ("polymers", "dehydration synthesis", "protein structure", "nucleic acids"),
        "Polymerization energetics and sequence-to-structure reasoning.",
        "Classify molecules from structural evidence rather than names alone.",
        "Use chemical tests and structural clues to identify biological macromolecules.",
        "Structure is not decoration; small chemical changes can redirect function and recognition.",
        "Given a molecular feature, infer likely solubility, interaction partners, or cellular role.",
        "Explain how a mutation, lipid substitution, or glycosylation change propagates to phenotype.",
        "biology.genetics.genetics.translate_mrna",
    ),
    _r(
        "unit_I_enzymes_and_kinetics",
        "Enzymes accelerate reactions by stabilizing transition states without changing thermodynamic endpoints.",
        ("activation energy", "Michaelis-Menten kinetics", "inhibition", "allostery"),
        "Michaelis-Menten, Lineweaver-Burk, and inhibition-pattern calculations.",
        "Fit or interpret enzyme-rate data and identify which parameter changed.",
        "Measure reaction-rate proxies and compare inhibition scenarios.",
        "A catalyst changes rate, not the equilibrium constant or the sign of delta G.",
        "Infer Vmax, Km, or inhibition type from data and justify the mechanistic interpretation.",
        "Apply enzyme-kinetic reasoning to drug dosing, metabolic control, or diagnostic assays.",
        "biology.biochemistry.biochemistry.michaelis_menten",
    ),
    _r(
        "unit_II_cell_theory",
        "Cells are bounded, evolving systems whose size and organization reflect physical constraints.",
        ("cell theory", "surface area", "microscopy", "prokaryote/eukaryote comparison"),
        "Surface-area-to-volume scaling.",
        "Infer cellular constraints from measurements, micrographs, and scale bars.",
        "Compare cell types and quantify surface-area limits.",
        "Cells are not just small bags of fluid; boundaries and internal organization create function.",
        "Use size or microscopy evidence to classify a cell and predict a constraint on exchange.",
        "Transfer scale reasoning to eggs, neurons, root hairs, and microbial colonies.",
        "biology.cell.cell_biology.diffusion_flux",
    ),
    _r(
        "unit_II_cell_structure",
        "Organelle structure partitions work, traffic, information, and energy inside eukaryotic cells.",
        ("organelles", "endomembrane system", "cytoskeleton", "motor proteins"),
        "Compartment-flow and motor-transport calculations.",
        "Trace a molecule through compartments using evidence from labels or perturbations.",
        "Map organelle function with microscopy-style observations.",
        "Organelles are dynamic process hubs, not static textbook icons.",
        "Predict which organelle or cytoskeletal process is disrupted from a phenotype.",
        "Apply compartment logic to secretion, apoptosis, infection, or cell division.",
        "biology.cell.cell_biology.ORGANELLES",
    ),
    _r(
        "unit_II_membrane_transport",
        "Membranes convert gradients, permeability, and selective transport into cellular physiology.",
        ("bilayers", "diffusion", "osmosis", "electrochemical gradients"),
        "Nernst, Goldman, osmotic, and facilitated-transport calculations.",
        "Interpret transport data from gradients, rates, and membrane potentials.",
        "Test osmosis and transport mechanisms with simple cell or model-membrane observations.",
        "Equilibrium does not mean equal concentration; charge and permeability matter.",
        "Calculate or predict ion movement and explain which force dominates.",
        "Transfer gradient logic to neurons, kidneys, roots, and mitochondrial membranes.",
        "biology.cell.cell_biology.nernst_potential",
    ),
    _r(
        "unit_II_cell_signaling",
        "Cells communicate by converting external signals into regulated intracellular decisions.",
        ("receptors", "second messengers", "signal amplification", "feedback"),
        "Ligand-receptor occupancy and dose-response reasoning.",
        "Read pathway diagrams and infer the effect of agonists, antagonists, or mutations.",
        "Model signaling response from receptor activation to cellular output.",
        "A pathway diagram is a causal model, not a memorization chart.",
        "Predict the outcome of perturbing one pathway component and justify the causal chain.",
        "Apply signaling logic to hormones, neurotransmitters, immune receptors, or cancer mutations.",
        "biology.physiology.physiology.homeostasis_response",
    ),
    _r(
        "unit_III_bioenergetics_and_respiration",
        "Cells harvest free energy by coupling redox chemistry to phosphoryl transfer and ion gradients.",
        ("free energy", "redox", "glycolysis", "oxidative phosphorylation"),
        "Delta G, ATP yield, and electron-carrier accounting.",
        "Track carbon, electrons, and ATP across a pathway.",
        "Estimate energy yield under aerobic and anaerobic conditions.",
        "ATP is not stored energy in a vague sense; it is a coupling currency with defined reaction chemistry.",
        "Calculate an energy yield or redox consequence and connect it to cellular work.",
        "Transfer energy accounting to exercise, fermentation, hypoxia, and mitochondrial disease.",
        "biology.biochemistry.biochemistry.glycolysis_summary",
    ),
    _r(
        "unit_III_photosynthesis",
        "Photosynthesis couples light-driven electron flow to carbon fixation and planetary productivity.",
        ("photosystems", "electron transport", "Calvin cycle", "photorespiration"),
        "Photon, ATP/NADPH, and Calvin-cycle stoichiometry.",
        "Interpret light-response and carbon-fixation data.",
        "Measure or model photosynthetic rate under changing light or carbon conditions.",
        "Plants do not eat sunlight; they use light energy to reduce carbon using electrons and enzymes.",
        "Compute carbon-fixation requirements and explain a limiting factor.",
        "Transfer photosynthetic constraints to crops, algae, climate, or ecosystem productivity.",
        "biology.botany.botany.photosynthesis_rate",
    ),
    _r(
        "unit_III_metabolic_integration",
        "Metabolism is a regulated network that reallocates flux across tissues, time, and nutrient states.",
        ("flux", "energy charge", "hormonal control", "fed/fasted states"),
        "Energy charge, control points, and pathway-flux comparisons.",
        "Use pathway evidence to infer which metabolic state or tissue is active.",
        "Compare metabolic responses across nutrient and hormone conditions.",
        "A pathway is not a one-way assembly line; reversibility and regulation define the real route.",
        "Predict how a change in substrate, hormone, or enzyme activity redirects flux.",
        "Apply metabolic network reasoning to diabetes, fasting, exercise, or cancer metabolism.",
        "biology.biochemistry.biochemistry.reaction_free_energy",
    ),
    _r(
        "unit_IV_dna_replication_and_cell_cycle",
        "Genome copying is accurate because chemistry, enzyme proofreading, and checkpoints cooperate.",
        ("semiconservative replication", "polymerase", "proofreading", "checkpoints"),
        "Replication-fork speed, error-rate, and cell-cycle timing calculations.",
        "Interpret replication or cell-cycle data from timing, labeling, or checkpoint perturbations.",
        "Model replication dynamics and checkpoint outcomes.",
        "High fidelity is not automatic; it is built from multiple partially redundant safeguards.",
        "Calculate replication timing or error burden and infer checkpoint consequences.",
        "Transfer replication logic to cancer, aging, viral replication, or antibiotic targets.",
        "biology.genetics.genetics.dna_complement",
    ),
    _r(
        "unit_IV_gene_expression",
        "Gene expression translates sequence information into regulated RNA and protein products.",
        ("transcription", "translation", "codons", "RNA processing"),
        "Reading-frame, codon, and expression-output calculations.",
        "Convert DNA/RNA sequence data into predicted molecular products.",
        "Trace expression from DNA template to protein or regulatory RNA.",
        "A gene is not simply a protein recipe; context controls when, where, and how much product appears.",
        "Translate or annotate a sequence and explain how a regulatory change alters output.",
        "Apply expression logic to mutations, biotechnology, development, and disease diagnostics.",
        "biology.genetics.genetics.translate_mrna",
    ),
    _r(
        "unit_IV_mutations_and_genomics",
        "Genomic variation becomes biological consequence through sequence context, repair, and selection.",
        ("mutation classes", "DNA repair", "CRISPR", "genome analysis"),
        "Mutation-rate, edit-efficiency, and sequence-comparison calculations.",
        "Classify variants and predict likely molecular effect from sequence evidence.",
        "Evaluate genome-editing or variant-calling scenarios.",
        "Not every mutation is harmful, and not every harmful mutation changes a protein sequence.",
        "Predict the impact of a variant and justify the evidence needed to validate it.",
        "Transfer variant reasoning to cancer genomics, ancestry, gene therapy, or microbial evolution.",
        "biology.genetics.genetics.hamming_distance",
    ),
    _r(
        "unit_IV_chromatin_and_epigenetic_mechanisms",
        "Cells create stable yet reversible expression states through chromatin, DNA marks, and regulatory circuits.",
        ("chromatin", "methylation", "histone modification", "enhancers"),
        "Regulatory-state and expression-ratio reasoning.",
        "Interpret chromatin or expression evidence from simple regulatory datasets.",
        "Compare regulatory perturbations and predicted expression outputs.",
        "Epigenetic does not mean independent of DNA sequence or permanently inherited.",
        "Explain how a regulatory mark changes accessibility and predict downstream expression.",
        "Apply regulation logic to differentiation, imprinting, cancer, or environmental responses.",
        "biology.genetics.genetics.cpg_methylation_remaining",
    ),
    _r(
        "unit_IV_epigenetic_inheritance_and_disease",
        "Three-dimensional genome organization and epigenetic inheritance link regulatory architecture to disease phenotypes.",
        ("3D genome", "phase separation", "imprinting", "epigenetic inheritance"),
        "Chromatin-loop, inheritance, and disease-risk reasoning.",
        "Interpret Hi-C, imprinting, or transgenerational datasets with causal caution.",
        "Compare inheritance models and predict disease consequences of regulatory disruption.",
        "A chromatin contact map is not proof of function without perturbation.",
        "Explain how 3D organization or inherited marks alter expression and disease risk.",
        "Apply inheritance logic to cancer, developmental disorders, and environmental exposure.",
        "biology.genetics.genetics.histone_modification_state",
    ),
    _r(
        "unit_V_mendelian_principles",
        "Mendelian segregation and probability explain inheritance when alleles assort independently.",
        ("segregation", "independent assortment", "Punnett squares", "probability"),
        "Punnett, binomial, and chi-square calculations.",
        "Use cross data to infer genotype probabilities.",
        "Solve monohybrid and dihybrid crosses and test expected ratios.",
        "Dominant does not mean common, stronger, or better.",
        "Compute a genetic probability or chi-square result and explain the biological assumption.",
        "Transfer Mendelian probability to model organisms and introductory human genetics.",
        "biology.genetics.genetics.chi_squared_test",
    ),
    _r(
        "unit_V_mendelian_extensions_and_human_genetics",
        "Extensions to Mendelian ratios and human pedigree analysis reveal when simple dominance fails.",
        ("incomplete dominance", "epistasis", "pedigrees", "penetrance"),
        "Pedigree, epistasis, and multi-locus probability calculations.",
        "Infer inheritance mode and extension mechanism from family or cross data.",
        "Solve pedigree and extension problems with explicit assumptions.",
        "A single-gene model is a starting hypothesis, not the default for every trait.",
        "Use pedigree or extension evidence to justify an inheritance diagnosis.",
        "Transfer extension reasoning to counseling, GWAS interpretation, and breeding.",
        "biology.genetics.genetics.punnett_square",
    ),
    _r(
        "unit_V_chromosomal_inheritance",
        "Genes travel on chromosomes, so linkage, recombination, and chromosome structure shape inheritance.",
        ("linkage", "recombination", "sex linkage", "chromosomal rearrangements"),
        "Recombination frequency and three-point mapping.",
        "Infer gene order or chromosomal mechanism from offspring counts.",
        "Map linked genes and reason from chromosomal anomalies.",
        "Independent assortment applies to unlinked loci, not to every pair of genes.",
        "Use progeny classes to calculate map distances and infer the most likely gene order.",
        "Transfer linkage reasoning to disease mapping, breeding, and genome assemblies.",
        "biology.genetics.genetics.infer_three_point_order",
    ),
    _r(
        "unit_V_population_genetics",
        "Allele frequencies change when assumptions about random mating, population size, and fitness are violated.",
        ("Hardy-Weinberg", "selection", "mutation", "genetic drift"),
        "Hardy-Weinberg and allele-frequency recurrence calculations.",
        "Estimate genotype or allele frequencies from population data.",
        "Test equilibrium and model allele-frequency change.",
        "Hardy-Weinberg is a null model, not a claim that populations do not evolve.",
        "Calculate expected frequencies and identify which evolutionary force could explain deviations.",
        "Apply population-genetic reasoning to screening, conservation, and pathogen evolution.",
        "biology.genetics.genetics.hardy_weinberg",
    ),
    _r(
        "unit_VI_evolution_and_selection",
        "Natural selection is differential reproductive success acting on heritable variation in context.",
        ("variation", "fitness", "adaptation", "selection coefficient"),
        "Selection coefficient and allele-frequency trajectory calculations.",
        "Interpret fitness data and distinguish selection from other forces.",
        "Simulate selection across generations under alternative fitness assumptions.",
        "Evolution is not goal-directed progress; it is local change in populations under constraints.",
        "Estimate selection strength from data and explain why the result is context dependent.",
        "Transfer selection reasoning to antibiotics, pesticide resistance, cancer, or climate adaptation.",
        "biology.evolution.evolution.simulate_selection",
    ),
    _r(
        "unit_VI_genetic_drift_and_speciation",
        "Chance, population structure, and barriers to gene flow can generate divergence even without adaptive change.",
        ("drift", "effective population size", "gene flow", "speciation"),
        "Fixation probability, effective population size, and migration-selection balance.",
        "Distinguish stochastic from directional change in allele-frequency data.",
        "Model drift and speciation scenarios with repeated trials.",
        "Random does not mean patternless; stochastic processes have predictable distributions.",
        "Predict how population size or isolation changes divergence and fixation risk.",
        "Apply drift reasoning to endangered populations, founder effects, and island radiations.",
        "biology.evolution.evolution.simulate_drift",
    ),
    _r(
        "unit_VI_phylogenetics",
        "Phylogenies are evidence-based hypotheses about ancestry, not ladders of progress.",
        ("homology", "tree topology", "parsimony", "molecular clocks"),
        "Tree-distance, parsimony, and molecular-clock calculations.",
        "Read trees correctly and map traits or sequences onto branches.",
        "Infer relationships from character or sequence evidence.",
        "Living species are cousins, not ancestors of one another.",
        "Use a tree to infer shared ancestry, character transitions, or divergence time.",
        "Transfer tree thinking to pathogens, conservation units, gene families, and development.",
        "biology.genetics.genetics.jukes_cantor_distance",
    ),
    _r(
        "unit_VII_bacteria_archaea_viruses",
        "Microbial diversity reflects different cell architectures, genomes, metabolisms, and evolutionary histories.",
        ("prokaryotic structure", "archaea", "viruses", "horizontal gene transfer"),
        "Growth-rate, genome-size, and dilution calculations.",
        "Interpret microbial observations from growth, sequence, or structural evidence.",
        "Measure growth and compare microbial life strategies.",
        "Viruses are not simply tiny bacteria; they use fundamentally different replication logic.",
        "Classify a microbe or virus from evidence and predict a likely vulnerability.",
        "Apply microbial diversity reasoning to antibiotics, biotechnology, ecology, and outbreaks.",
        "biology.microbiology.microbiology.bacterial_growth_curve",
    ),
    _r(
        "unit_VII_microbial_ecology",
        "Microbes organize communities, cycles, and host physiology through interactions and metabolism.",
        ("microbiomes", "symbiosis", "diversity", "biogeochemical cycling"),
        "Diversity indices, richness estimates, and interaction-network reasoning.",
        "Compute or interpret community metrics from abundance data.",
        "Compare microbial communities and infer interaction hypotheses.",
        "A microbiome is not automatically beneficial; context determines the effect.",
        "Use community data to infer diversity, dominance, and a plausible ecological mechanism.",
        "Transfer microbial ecology to soils, oceans, digestion, disease, and climate feedbacks.",
        "biology.ecology.ecology.biodiversity_indices",
    ),
    _r(
        "unit_VII_host_immunity_and_vaccines",
        "Host immunity and vaccination reshape pathogen transmission by changing susceptible fractions.",
        ("innate immunity", "adaptive immunity", "vaccination", "herd immunity"),
        "Herd-immunity threshold and basic immunological reasoning.",
        "Interpret antibody, cellular, and vaccine-response evidence.",
        "Compare immune mechanisms and vaccination scenarios.",
        "Immunity is not binary; timing, dose, and variant matter.",
        "Predict how immunity or vaccination changes individual and population risk.",
        "Transfer immunity reasoning to outbreak response and clinical decision-making.",
        "biology.microbiology.microbiology.sir_model",
    ),
    _r(
        "unit_VII_antimicrobial_resistance_and_epidemiology",
        "Antimicrobial resistance and epidemic dynamics emerge from pathogen evolution and transmission networks.",
        ("antibiotic resistance", "R0", "transmission", "surveillance"),
        "R0, resistance-mechanism, and outbreak-trajectory calculations.",
        "Interpret resistance assays and outbreak curves.",
        "Model transmission and compare resistance-control strategies.",
        "R0 is not a fixed property of a pathogen alone; it depends on host behavior and environment.",
        "Calculate a threshold or outbreak trajectory and identify the intervention lever.",
        "Transfer resistance and epidemiology reasoning to stewardship and public-health policy.",
        "biology.microbiology.microbiology.sir_model",
    ),
    _r(
        "unit_VIII_plant_structure_and_water",
        "Plant form is an engineering solution to water movement, support, gas exchange, and growth.",
        ("xylem", "phloem", "water potential", "transpiration"),
        "Water-potential and transpiration-flux calculations.",
        "Interpret plant-water data from pressure, solute, and humidity measurements.",
        "Measure or model water movement through plant tissues.",
        "Water does not move because plants pull with intention; it follows potential gradients and cohesion.",
        "Calculate water potential and predict the direction of water movement.",
        "Transfer plant-water reasoning to drought, irrigation, forest physiology, and crop breeding.",
        "biology.botany.botany.water_potential",
    ),
    _r(
        "unit_VIII_plant_reproduction",
        "Plant reproduction integrates life cycles, development, dispersal, and environmental timing.",
        ("alternation of generations", "flowers", "seeds", "development"),
        "Life-cycle accounting and phyllotaxis/growth-pattern calculations.",
        "Track ploidy, tissue origin, and reproductive stage from diagrams or observations.",
        "Compare reproductive structures and developmental outcomes.",
        "Pollen, spores, seeds, and gametes are not interchangeable terms.",
        "Trace a plant life cycle and predict the consequence of disrupting one stage.",
        "Transfer reproductive reasoning to agriculture, pollination ecology, and plant evolution.",
        "biology.botany.botany.plant_biomass_growth",
    ),
    _r(
        "unit_VIII_plant_responses",
        "Plants sense environmental signals and respond through growth, hormones, and physiological regulation.",
        ("tropisms", "hormones", "photoperiodism", "stress responses"),
        "Dose-response, water-use-efficiency, and hormone-interaction reasoning.",
        "Interpret plant response data across light, gravity, water, and hormone treatments.",
        "Test plant response predictions under controlled environmental cues.",
        "A plant response is not passive; plants actively regulate development and physiology without neurons.",
        "Predict a plant response from a signal and identify the likely hormone or pathway.",
        "Transfer response logic to shade avoidance, drought, flowering, and crop management.",
        "biology.botany.botany.photosynthesis_rate",
    ),
    _r(
        "unit_IX_circulation_respiration_homeostasis",
        "Animal transport systems maintain gradients that let cells exchange gases, nutrients, heat, and wastes.",
        ("cardiac output", "gas exchange", "homeostasis", "feedback"),
        "Cardiac-output, diffusion, oxygen-saturation, and feedback calculations.",
        "Interpret physiological data from pressure, flow, saturation, or set-point changes.",
        "Model circulation, respiration, and feedback compensation.",
        "Homeostasis is dynamic regulation, not an unchanging internal state.",
        "Calculate a transport or feedback variable and explain the compensatory response.",
        "Transfer homeostatic reasoning to exercise, altitude, hemorrhage, fever, and shock.",
        "biology.physiology.physiology.oxygen_saturation",
    ),
    _r(
        "unit_IX_nervous_system",
        "Nervous systems compute with cells whose structure shapes information flow and behavior.",
        ("neurons", "glia", "circuits", "sensory processing"),
        "Cable-length, conduction, and simple circuit calculations.",
        "Interpret neural data from anatomy, timing, or lesion evidence.",
        "Map circuit structure onto predicted information flow.",
        "The brain is not only neurons; glia and circuit context are essential to function.",
        "Predict behavioral or signal consequences from a circuit or structural perturbation.",
        "Transfer circuit reasoning to reflexes, sensory systems, learning, and disease.",
        "biology.neuroscience.neuroscience.cable_voltage_attenuation",
    ),
    _r(
        "unit_IX_action_potential_synapses",
        "Electrical excitability and synaptic transmission convert ion gradients into rapid communication.",
        ("action potentials", "ion channels", "synapses", "plasticity"),
        "Nernst/Goldman, Hodgkin-Huxley, and synaptic-current reasoning.",
        "Interpret voltage traces, conductance changes, and synaptic perturbations.",
        "Model excitability and synaptic response under changed ion or channel conditions.",
        "An action potential is not electricity flowing like a wire; it is regenerated ion-channel dynamics.",
        "Predict how changing an ion gradient or channel conductance alters excitability.",
        "Transfer excitability reasoning to anesthesia, toxins, epilepsy, and neuromuscular disease.",
        "biology.neuroscience.neuroscience.action_potential_hh",
    ),
    _r(
        "unit_IX_endocrine_signaling",
        "Hormone feedback loops coordinate long-range physiological homeostasis.",
        ("hormones", "feedback", "receptors", "homeostasis"),
        "Hormone feedback and dose-response reasoning.",
        "Interpret endocrine time courses, panels, and perturbations.",
        "Compare endocrine axes and feedback scenarios.",
        "A hormone surge is not always pathological; context and set-point matter.",
        "Predict the consequence of changing a hormone, receptor, or axis set-point.",
        "Transfer endocrine reasoning to metabolism, stress, and development.",
        "biology.physiology.physiology.homeostasis_response",
    ),
    _r(
        "unit_IX_immune_system_defense",
        "Innate and adaptive immunity integrate recognition, effector function, tolerance, and memory.",
        ("innate immunity", "adaptive immunity", "tolerance", "immunotherapy"),
        "Immune-memory, cytokine, and recognition reasoning.",
        "Interpret immune titers, cytokine profiles, or perturbation data.",
        "Compare innate and adaptive activation scenarios.",
        "Immunity is not just attack; recognition, tolerance, memory, and regulation are equally central.",
        "Predict the consequence of changing an antigen, cell population, or checkpoint.",
        "Transfer immunity reasoning to vaccination, autoimmunity, infection, and cancer therapy.",
        "biology.physiology.physiology.homeostasis_response",
    ),
    _r(
        "unit_X_population_ecology",
        "Population change reflects births, deaths, movement, age structure, and density dependence.",
        ("exponential growth", "logistic growth", "life tables", "population viability"),
        "Exponential/logistic growth, mark-recapture, and matrix projection.",
        "Use abundance or age-structure data to estimate growth and risk.",
        "Model population trajectories and compare sampling methods.",
        "Carrying capacity is not a fixed magic number; it changes with resources, interactions, and disturbance.",
        "Calculate a growth or sampling parameter and interpret its conservation meaning.",
        "Transfer population models to fisheries, invasive species, epidemiology, and endangered species.",
        "biology.ecology.ecology.logistic_growth",
    ),
    _r(
        "unit_X_community_interactions",
        "Communities are structured by pairwise species interactions and successional change.",
        ("competition", "predation", "mutualism", "succession"),
        "Lotka-Volterra-style interaction reasoning.",
        "Interpret abundance, interaction, or disturbance data from communities.",
        "Compare species-interaction outcomes under changing conditions.",
        "A species interaction is not permanently good or bad; the sign can change with context.",
        "Predict how changing one species or resource alters community structure.",
        "Transfer interaction reasoning to restoration, agriculture, and invasion biology.",
        "biology.ecology.ecology.biodiversity_indices",
    ),
    _r(
        "unit_X_biodiversity_and_food_webs",
        "Biodiversity patterns, food webs, and island biogeography scale from local interactions to landscape structure.",
        ("food webs", "keystone species", "species-area", "diversity indices"),
        "Shannon, species-area, and network connectance reasoning.",
        "Interpret food-web, richness, or biogeography datasets.",
        "Compare diversity and network scenarios under area or disturbance change.",
        "Richness alone does not equal functional stability.",
        "Calculate a diversity or species-area metric and interpret its ecological meaning.",
        "Transfer biodiversity reasoning to conservation planning and habitat fragmentation.",
        "biology.ecology.ecology.species_area_relationship",
    ),
    _r(
        "unit_X_ecosystem_ecology",
        "Ecosystems couple energy flow and matter cycling across organisms, environments, and time.",
        ("primary productivity", "trophic efficiency", "nutrient cycles", "decomposition"),
        "Energy-flow, productivity, and nutrient-budget calculations.",
        "Trace matter and energy through food webs and biogeochemical cycles.",
        "Quantify ecosystem fluxes and identify limiting pools.",
        "Energy flows through ecosystems, but matter cycles; confusing the two breaks many explanations.",
        "Calculate a flux or efficiency and explain which pool or process limits the system.",
        "Transfer ecosystem reasoning to eutrophication, carbon budgets, agriculture, and climate feedback.",
        "biology.ecology.ecology.food_web_trophic_levels",
    ),
    _r(
        "unit_X_biomes_and_conservation",
        "Biodiversity patterns and conservation decisions emerge from climate, history, disturbance, and human choice.",
        ("biomes", "biodiversity", "extinction risk", "conservation planning"),
        "Species-area, risk, and prioritization calculations.",
        "Use maps, trend data, and threat categories to justify conservation priorities.",
        "Compare biome patterns and conservation tradeoffs.",
        "Conservation is decision-making under constraints and uncertainty, not only preserving untouched nature.",
        "Evaluate a conservation scenario using evidence, tradeoffs, and uncertainty.",
        "Transfer conservation reasoning to land use, climate corridors, restoration, and environmental justice.",
        "biology.ecology.ecology.species_area_relationship",
    ),
)


CURRICULUM_BY_ID: dict[str, CurriculumRecord] = {record.chapter_id: record for record in CURRICULUM}


def by_id(chapter_id: str) -> CurriculumRecord | None:
    return CURRICULUM_BY_ID.get(chapter_id)


def require(chapter_id: str) -> CurriculumRecord:
    record = by_id(chapter_id)
    if record is None:
        raise KeyError(f"No curriculum record for {chapter_id}")
    return record


__all__ = ["CurriculumRecord", "CURRICULUM", "CURRICULUM_BY_ID", "by_id", "require"]
