"""Assessment-surface pattern catalogs."""

from __future__ import annotations

import re

ALLOWED_ADVISORY_CLASSIFICATIONS = {
    "valid_scientific_absolute",
    "needs_qualifier",
    "copyedit_artifact",
}

EXPECTED_CONFIGURED_SURFACE_COUNTS = {
    "front_matter": 2,
    "unit_intro": 11,
    "chapter": 44,
    "lab": 44,
    "question": 44,
    "appendix": 7,
}


QUESTION_GENERIC_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("generic-answer-define", re.compile(r"Give the canonical definition of")),
    ("generic-answer-define-broad", re.compile(r"Give the canonical definition")),
    ("generic-answer-mechanism", re.compile(r"Build a mechanistic answer")),
    ("generic-answer-numeric", re.compile(r"Numerical problem on")),
    ("generic-answer-position", re.compile(r"Take a position on \*")),
    ("generic-answer-design", re.compile(r"Propose an experimental or engineering response")),
    ("generic-answer-rubric", re.compile(r"Rubric for \*")),
    ("generic-answer-players", re.compile(r"name the relevant players")),
    ("generic-answer-scale-setting", re.compile(r"scale-setting detail")),
    ("generic-answer-thin-evidence", re.compile(r"state the judgment, cite two lines of evidence")),
    ("generic-answer-thin-numeric", re.compile(r"identify the governing equation or ratio")),
    ("generic-answer-thin-design", re.compile(r"specify the manipulated variable")),
    ("generic-answer-key-prefix", re.compile(r"Answer key for \*")),
    ("generic-answer-define-precisely", re.compile(r"define the concept precisely")),
    ("generic-answer-scale", re.compile(r"place it at the correct biological scale")),
    ("generic-answer-causal-sequence", re.compile(r"trace the causal sequence")),
    ("generic-answer-equation-ratio", re.compile(r"choose the relevant equation, ratio, or probability model")),
    ("generic-answer-hypothesis-variable", re.compile(r"state the hypothesis, variable being changed")),
    ("generic-answer-judgment", re.compile(r"make a justified judgment")),
    ("generic-answer-vocab-pitfall", re.compile(r"giving a vocabulary-only answer")),
    ("generic-answer-name-term", re.compile(r"Name the term in ")),
    ("generic-answer-evidence-anchor", re.compile(r"Evidence anchor:")),
    ("generic-answer-credit-requires", re.compile(r"Credit requires an explicit mechanism")),
    ("generic-answer-prompt-linked", re.compile(r"prompt-linked evidence")),
    ("generic-answer-core-response", re.compile(r"Core response for \*")),
    ("generic-answer-expected-answer", re.compile(r"Expected answer for \*")),
    ("generic-answer-prompt-cues", re.compile(r"Prompt cues to cover:")),
    ("generic-answer-source-standard", re.compile(r"Source standard:")),
    ("generic-answer-common-pitfall", re.compile(r"Common pitfall:")),
    ("generic-answer-chapter-lens", re.compile(r"Chapter lens:")),
    ("generic-answer-governing-equation", re.compile(r"set up the governing equation")),
    ("generic-answer-defensible-judgment", re.compile(r"state a defensible judgment")),
    ("generic-answer-two-observations", re.compile(r"support it with two chapter-specific observations")),
    ("generic-answer-every-clause", re.compile(r"Answer every requested clause")),
    ("generic-answer-ground-cref", re.compile(r"Ground the answer in \\cref")),
    ("generic-answer-use-cref", re.compile(r"Use \\cref")),
    ("generic-answer-extend-cref", re.compile(r"Extend \\cref")),
    ("generic-answer-biological-players", re.compile(r"Name the biological players")),
    ("generic-answer-one-limitation", re.compile(r"name one limitation or counterexample")),
    ("generic-answer-boundary-condition", re.compile(r"boundary condition that prevents overgeneralizing")),
    ("generic-answer-boundary-condition-uk", re.compile(r"boundary condition that prevents overgeneralising")),
    ("generic-answer-carry-values", re.compile(r"Carry through these values:")),
    ("generic-answer-named-items", re.compile(r"Use these named items explicitly:")),
    ("generic-answer-current-define", re.compile(r"Define \*")),
    ("generic-answer-current-compare", re.compile(r"Compare \*")),
    ("generic-answer-current-solve", re.compile(r"Solve \*")),
    ("generic-answer-current-explain", re.compile(r"Explain \*")),
    ("generic-answer-current-design", re.compile(r"Design the test for \*")),
    ("generic-answer-current-evaluate", re.compile(r"Evaluate \*")),
    ("generic-answer-current-apply", re.compile(r"Apply the chapter principle to \*")),
    ("generic-answer-current-required-clauses", re.compile(r"Required clauses:")),
    ("generic-answer-current-values", re.compile(r"Use the stated values explicitly:")),
    ("generic-answer-current-named-evidence", re.compile(r"Named evidence to include:")),
    ("generic-answer-current-first-noun", re.compile(r"Do not stop at the first noun phrase")),
    ("generic-answer-current-anchor", re.compile(r"Anchor the response to \\cref")),
    ("generic-answer-complete-response", re.compile(r"A complete response should")),
    ("generic-answer-expected-reasoning", re.compile(r"Expected reasoning:")),
    ("generic-answer-scoring-focus", re.compile(r"Scoring focus:")),
    ("generic-answer-key-label", re.compile(r"Key answer:")),
    ("generic-answer-comparison-label", re.compile(r"Comparison answer:")),
    ("generic-answer-calculation-label", re.compile(r"Calculation answer:")),
    ("generic-answer-mechanistic-label", re.compile(r"Mechanistic answer:")),
    ("generic-answer-design-label", re.compile(r"Design answer:")),
    ("generic-answer-evaluation-label", re.compile(r"Evaluation answer:")),
    ("generic-answer-application-label", re.compile(r"Application answer:")),
    ("generic-answer-chapter-evidence-label", re.compile(r"Chapter evidence:")),
    ("generic-answer-evidence-check-label", re.compile(r"Evidence check:")),
    ("generic-answer-trace-star", re.compile(r"Trace \*")),
    ("generic-answer-precise-account", re.compile(r"Give a precise account of \*")),
    ("generic-answer-write-model", re.compile(r"Write the model for \*")),
    ("generic-answer-turn-star", re.compile(r"Turn \*")),
    ("generic-answer-assess-star", re.compile(r"Assess \*")),
    ("generic-answer-use-principle", re.compile(r"Use the chapter principle with \*")),
    ("generic-answer-reference-point", re.compile(r"Reference point: \\cref")),
    ("generic-answer-v3-mechanism", re.compile(r"should first state the chapter.s concrete mechanism")),
    ("generic-answer-v3-causal-chain", re.compile(r"should give the causal chain")),
    ("generic-answer-v3-shared-principle", re.compile(r"should name the shared biological principle")),
    ("generic-answer-v3-model-substitute", re.compile(r"should name the model, substitute the stated values")),
    ("generic-answer-v3-scholarship-standard", re.compile(r"Scholarship standard:")),
    ("generic-answer-v3-pitfall", re.compile(r"Pitfall to avoid:")),
    ("generic-answer-v3-chapter-anchor", re.compile(r"Chapter anchor:")),
    (
        "generic-answer-v3-same-scale",
        re.compile(r"Then give one same-scale example or boundary condition using this evidence"),
    ),
    ("generic-answer-v3-decisive-contrast", re.compile(r"The decisive contrast or boundary condition is")),
    ("generic-answer-v3-interpret-outcome", re.compile(r"Interpret the outcome using:")),
    ("mismatched-popgen-tail", re.compile(r"propose one comparative or population-genomic test")),
    ("mismatched-clinical-tail", re.compile(r"propose one clinical intervention")),
    ("mismatched-molecular-tail", re.compile(r"propose one molecular intervention")),
)

# Substring phrases that identify v1 heuristic answers in question banks.
# Shared with `biology.answer_refinement.classification.is_v1_generated`.
ANSWER_REFINEMENT_SIGNATURES: tuple[str, ...] = (
    "This question asks for a definition or factual statement about:",
    "Construct a side-by-side contrast of",
    "This is a numerical problem. Begin by stating the formula",
    "Give a mechanistic explanation for *",
    "Outline an experimental or design response to the prompt on *",
    "Take a position on *",
    "Apply the chapter's framework to the specific scenario:",
    "Give the canonical definition of *",
    "Contrast the items in *",
    "Numerical problem on *",
    "Build a mechanistic answer to *",
    "Propose an experimental or engineering response to *",
    "Apply the chapter's principles to the scenario:",
    "Expected answer for *",
    "Prompt cues to cover:",
    "Source standard:",
    "Common pitfall:",
    "Chapter lens:",
    "boundary condition that prevents overgeneralizing it",
    "Answer every requested clause rather than only the opening phrase",
    "Ground the answer in \\cref{",
    "Use \\cref{",
    "Extend \\cref{",
    "Carry through these values:",
    "Use these named items explicitly:",
    "set up the governing equation",
    "state a defensible judgment",
    "support it with two chapter-specific observations",
    "Name the biological players",
    "Ground the answer in \\cref",
    "Use \\cref",
    "Extend \\cref",
    "Define *",
    "Compare *",
    "Solve *",
    "Explain *",
    "Design the test for *",
    "Evaluate *",
    "Apply the chapter principle to *",
    "Required clauses:",
    "Use the stated values explicitly:",
    "Named evidence to include:",
    "Do not stop at the first noun phrase",
    "Anchor the response to \\cref",
    "A complete response should",
    "Expected reasoning:",
    "Scoring focus:",
    "Trace *",
    "Give a precise account of *",
    "Set *",
    "Write the model for *",
    "Turn *",
    "Assess *",
    "Use the chapter principle with *",
    "Reference point: \\cref",
    "Key answer:",
    "Comparison answer:",
    "Calculation answer:",
    "Mechanistic answer:",
    "Design answer:",
    "Evaluation answer:",
    "Application answer:",
    "Chapter evidence:",
    "Recent and numeric claims should remain tied to authoritative sources",
)
